variable "region" {}
variable "security_group" {}
variable "key_name" {}
variable "instance_type" {}
variable "instance_ami" {}
variable "ec2_name" {}
variable "instance_count" {}
variable "ec2_user" {}
variable "iam_instance_profile" {}
variable "profile" {}
variable "spot_price" {}
